source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'WTLibrary_Example', :exclusive => true do
  pod "WTLibrary", :path => "../"
end

target 'WTLibrary_Tests', :exclusive => true do
  pod "WTLibrary", :path => "../"

  
end
